version: "3.7"
services:
    #nexus sonartype
    nexus: 
      image: sonatype/nexus3:3.37.0
      ports:
        - 8001:8081
      volumes:
        - nexus-data:/nexus-data
    #Jenkins container
    jenkins:
      build:
        context: ./jenkins
      image: lqssjenkins:latest
      container_name: jenkins
      ports:
        - 8002:8080
        - 50000:50000
      privileged: true
      volumes:
          - jenkinsd-data:/var/jenkins_home
          - /jenkins/secrets:/var/jenkins_home/secrets
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker     
      networks:
        - cicd  
    #sonarqube container     
    sonarqube:
      depends_on:
        - db
      image: sonarqube:7.6-community
      #image: sonarqube:6.7
      container_name: sonarqube      
      volumes:
        - sonarqube_conf:/opt/sonarqube/conf
        - sonarqube_data:/opt/sonarqube/data
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins   
      networks:
        - cicd
      ports:
        - '8003:9000'
      #entrypoint: /opt/sonarqube/start.sh
      environment:
        - USER_LOGIN=admin
        - USER_NAME=admin
        - USER_PASSWORD=adminadmin
      #  - SONARQUBE_JDBC_USERNAME=root
      #  - SONARQUBE_JDBC_PASSWORD=root
      #  - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

    #Mysql db setup    
    db:
      image: mysql:5.7.32
      container_name: mysqldb
      restart: always
      ports:
        - '3306:3306'
      volumes:
          - mysql-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=sonarqube
      networks:
        - cicd
    #Phpmyadmin setup            
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin:5.1.1
      container_name: phpmyadmin
      restart: always
      ports:
        - '8004:80'
      environment:
        PMA_HOST: db    
      networks:
        - cicd                          
networks:
  cicd:
    driver: bridge
volumes:
  nexus-data:
  mysql-data:
  jenkinsd-data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

