version: "3.7"
services:
  #sonartype nexus3
  nexus:
    image: sonatype/nexus3:3.37.0
    container_name: nexus3
    restart: always
    ports:
      - ${NEXUS_PORT}:8081
    volumes:
      - nexus-data:/nexus-data
    networks:
      - cicd
  #Jenkins container
  jenkins:
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
      args:
        - MAVEN_V=${MAVEN_VERSION}
        - JENKINS_USER=${JENKINS_USER}
        - JENKINS_PASS=${JENKINS_PASS}
        - DOCKER_USER=${DOCKER_USER}
        - DOCKER_PASS=${DOCKER_PASS}
        - JENKINS_PORT=${JENKINS_PORT}
    container_name: jenkins
    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    privileged: true
    volumes:
      - "./jenkins/settings.xml:/opt/apache-maven-${MAVEN_VERSION}/conf/settings.xml" # For the nexus server setup
      - "./jenkins/mailer-config:/var/jenkins_home/JCasC/mailer-conf.yaml" # For the JCasC
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - cicd
  #sonarqube container     
  sonarqube:
    depends_on:
      - db
    image: sonarqube:7.6-community
    container_name: sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - cicd
    ports:
      - '${SONAR_PORT}:9000'
    environment:
      - USER_LOGIN=${SONAR_USER_LOGIN}
      - USER_NAME=${SONAR_USER_NAME}
      - USER_PASSWORD=${SONAR_USER_PASSWORD}
    #  - SONARQUBE_JDBC_USERNAME=root
    #  - SONARQUBE_JDBC_PASSWORD=root
    #  - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

    #Mysql db setup    
  db:
    image: mysql:5.7.32
    container_name: mysqldb
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_INIT_DATABASE} #Initial database
    networks:
      - cicd
  #Phpmyadmin setup            
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1.1
    container_name: phpmyadmin
    restart: always
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db
    networks:
      - cicd
networks:
  cicd:
    driver: bridge
volumes:
  nexus-data:
  mysql-data:
  jenkins_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

