version: "3.7"
services:
    # Spting boot app
    spring_boot_app:
      build:
        context: ./spring-app
      ports:
        - "8080:8082"
      networks:
        - cicd
    db:
      image: mysql
      container_name: mysqldb
      restart: always
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
      networks:
        - cicd
    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
        - '7000:80'
      environment:
        PMA_HOST: db    
      networks:
        - cicd                 
volumes:
  elasticsearch:
networks:
  cicd:
    driver: bridge


